### ISSUE TITLE
Alert Component

### ISSUE THREAD

**Issue by dvlden** [cpdevelops/simple.css#40]
> Related to issue #30 and pull request [33](https://github.com/cpdevelops/simple.css/pull/33) by [@mtoadvine](https://github.com/mtoadvine)

I am opening new issue as greed with project owner @cpdevelops and this is related to the Alert Component which requires a transition. _(e.g. fade effect)_

I have come up already with some solutions as I was asked by @cpdevelops to provide some example(s).

Let's begin with an easy approach.

1. Keeping Alert Component structure as is, with one additional paragraph as a wrapper for context.

In this HTML snippet, we can see Alert Component which applies `info` modifier class that changes alert to `blue` color. I just added one additional paragraph that serves as a context wrapper, because it's needed _(not a paragraph, in particular, could be div, but I think the paragraph is more suitable)_ in order to vertically align context with the close button. Also changed "X" into "&times;" which is I assume more accurate?

```html
<div class="alert info">
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque a error tenetur quo expedita pariatur soluta modi mollitia. Deserunt voluptas repellendus, sint sunt voluptatem doloremque repellat iure modi eius libero!
  </p>
  
  <span class="close">&times;</span>
</div>
```

In this SCSS snippet, we can see the whole Alert Component with some new additions and modifications. It relies on flexbox property in this case and browser support can be seen here:
[Can I Use?](http://caniuse.com/#search=flexbox). I think we can use it with confidence... Additional prefixes are not added because that will be handled by `Gulp` task runner and its addon called `Autoprefixer`.

```scss
.alert {
  position: relative;
  min-height: 50px;
  border-radius: 4px;
  margin-bottom: 20px;
  color: white;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: stretch;
  
  > p {
    padding: 15px;
  }
  
  .close {
    background-color: rgba(255, 255, 255, .4);
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 10px;
  }

  &.info {
    background-color: $info;
  }

  &.success {
    background-color: $success;
  }

  &.warning {
    background-color: $warning;
  }

  &.error {
    background-color: $error;
  }
}

.close {
  cursor: pointer;
  font-size: 1.4em;
}
```

In this JavaScript (jQuery dependent) snippet we target all `.alert` elements which contain the `.close` element inside of it and on click event on those, we search for its nearest class of `.alert` which are parent and we fade it out using the jQuery's function. I am unsure if this project should be jQuery dependent at all, so we could achieve the same thing with vanilla JavaScript, but with a bit more code. For this, I'd improve Gulp tasks and implement a `script` task as a module which would then build, compile, minify and do all those fancy terms out there to make it browser compatible.

```javascript
$(function () {
  $('.alert .close').on('click', function () {
    $(this).closest('.alert').fadeOut(320);
  });
});
```

This is how it would look with this approach:

<img width="414" alt="screen shot 2017-10-04 at 16 17 59" src="https://user-images.githubusercontent.com/3460368/31189009-27a144b0-a937-11e7-95a1-f349068ef58d.png">

Functional demo example can be found here:
[JS Fiddle Demo](https://jsfiddle.net/dvLden/24px5gvp/)

> Please let me know if I should make a PR with this component additions/changes and if so, I'll also improve Gulp tasks to support scripts and I'll suggest to ditch jQuery as dependency and write all required scripts in vanilla JS? Waiting for response and suggestions...
