### ISSUE TITLE
Create Containers

### ISSUE THREAD

**Issue by dvlden** [cpdevelops/simple.css#56]
**Explanation:**
Update `base.scss` with two new classes which can be used as app containers.

**How to:**
Find a proper place in the base file and write something like this (improve if you have ideas)

```scss
%container-props {
  width: 100%;
  padding: {
    right: 15px;
    left: 15px;
  }
  margin: {
    right: auto;
    left: auto;
  }
}

.container {
  @extend %container-props;
  
  @media (min-width: 576px) {
    max-width: 540px;
  }

  @media (min-width: 768px) {
    max-width: 720px;
  }

  @media (min-width: 992px) {
    max-width: 960px;
  }

  @media (min-width: 1200px) {
    max-width: 1140px;
  }

  &-fluid {
    @extend %container-props;
  }
}
```

> Quick Note: The code I wrote has not been tested. I rely on my mind and hope it works. Test before committing and make sure it works.

You also must update `index.html` and it should have two examples for containers.

1. `<div class="container"> ... </div>` - which should contain some content, maybe main content that already exists within the `body` as it should contain width and be responsive.

2. `<div class="container-fluid"> ... </div>` - which could contain some `lorem ipsum` dummy text, just to show that container has padding and no width.
